#!/bin/sh

# Install Composer
curl -sS https://getcomposer.org/installer | php

# Download all required composer packages
./composer.phar install --dev

# Setup Laravel With a new encryption key and migrate the database tables into existence
php artisan key:generate
php artisan optimize

# Build the DB Tables
php artisan migrate:install
php artisan migrate

# Seed the DB with data
php artisan db:seed

# Install Bower and Gulp Globally
npm install -g bower
npm install -g gulp

# Install all required modules
npm install

# save a local copy of gulp to this projects filesystem
npm install --save-dev gulp

# Update bower and pull in all dependencies
bower update